### ISSUE TITLE
[Feature Request] Open in New Window.

### ISSUE THREAD

**Issue by An-qi-Zhang** [darlal/obsidian-switcher-plus#63] opened 2022-07-12 21:00 UTC
Obsidian just updated the pop-out window function. It would be great to open a note in a new window, with ctrl+alt+enter, for example.

**Comment by darlal** [comment] 2022-07-13 01:27
This is already live in [release 2.0.2](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.0.2). `cmd+o` to open in new window for the custom modes (`headings`, `editor`, `related items`, `starred`, `symbol`) of the switcher. SwitcherPlus is designed to be a "drop-in" replacement for system, built-in switcher, as such, it tries really hard to not modify the system functionality as a principle. Thanks!

Duplicate of #60.

**Closed by darlal** 2022-07-13 01:27 UTC
Labels: duplicate
