### ISSUE TITLE
[Feature Request] always show filename firstly in the search result

### ISSUE THREAD

**Issue by Jackiexiao** [darlal/obsidian-switcher-plus#56] opened 2022-06-05 02:47 UTC
for example, when I search `question`, I want file with name `docs/notes/question` show in the first line of search result, since I use `heading mode search` to replace  obsidian's `quick switch`. filename has more weight than heading

![image](https://user-images.githubusercontent.com/18050469/172032775-8d5861d4-b6d7-4c9c-a1f6-1a57ae4d2793.png)

**Comment by darlal** [comment] 2022-06-12 18:53
When you search in `Headings` mode, it prioritizes matches against the headings contained in the file. If you instead use `standard` mode, that will prioritize matches against the filenames. Remove the `#` character and that will do what you're asking. This seems to be a duplicate of issue #47 which you also created.

**Comment by Jackiexiao** [comment] 2022-06-13 02:04
oh... I totally forget it... thx for your kindly reply. I wonder if we could add a option that `always show filename firstly in the search result` in `heading mode`

this is my use case, I use heading mode as my default and only switcher, I would like to search filename first, if nothing match, then I will look down to find if any heading match my need, `omnisearch` plugin is great(which can search everything), but it also a litter messy, sometimes it's hard to find what I want.

delete `#` works, but it's not convenient compare to the method I mentioned above

**Comment by darlal** [comment] 2022-06-20 11:26
Thanks for sharing the details of your workflow, that helps me understand what you're trying to achieve. What you describe is the opposite of how headings mode is designed to work. Headings mode will first search through headings for a file, then if there are no matches, it will fallback to searching the filename.

Here's something you could try to get what you are looking for, set `Quick Switcher++: Open` as your default shortcut mode, this will search and prioritize filename first. Then if you don't get the results you're looking for, add the `#` to the beginning of the query to perform a heading search. It still requires the additional keystroke to input `#`, but this switches up the order so that it matches with the workflow that you described.

**Comment by Jackiexiao** [comment] 2022-06-20 11:33
thx for your reply, but I still want to combined filename & heading mode. maybe I used `remnote` to take notes before, and I really miss remnote's "all in one" search...

maybe I will learn typescript someday and make a PR to implement this feature

**Comment by darlal** [comment] 2022-06-20 11:37
PRs are always welcomed! 😄

**Comment by darlal** [comment] 2022-06-25 10:55
> I still want to combined filename & heading mode

@Jackiexiao release [1.0.11](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.11) has a new option `Search filenames` which when enabled will always show filename match suggestions when in `Headings mode`. This should reduce the friction of having to do the additional keystrokes to switch between filename and headings in your workflow. Thanks!

**Closed by darlal** 2022-06-25 10:55 UTC
Labels: enhancement

**Comment by Jackiexiao** [comment] 2022-06-25 10:58
thx!!!!!

**Comment by Jackiexiao** [comment] 2022-06-25 11:15
it would be better if we could add option to prioritize filename instead heading in search result in heading mode (I know it sound a little weird) 

or, a better way to implement this feature is add a option to show heading when there is no filenames found in `Quick Switcher++: Open` (fall back to heading)

but any way, thx for developing this great plugin!
