### ISSUE TITLE
Select nearest symbol when performing "Open in Symbol Mode"

### ISSUE THREAD

**Issue by oin** [darlal/obsidian-switcher-plus#23] opened 2021-08-03 20:17 UTC
I'm a few weeks into Obsidian and I find Quick Switcher++ invaluable to do what I used to do in Sublime Text before: switching between headings in long documents using just the keyboard. I'm really grateful for your work!

However, a very important behavior of the Sublime symbol switcher is currently absent from Quick Switcher++, and it's really slowing me down when working inside long documents: starting from the nearest/current heading from the cursor when invoking _Open in Symbol Mode_.

Typically, I've got one log file per big project, with a h1 heading for each day, and further headings for subjects I've worked on. Every new day I append a new h1 heading and start taking notes. My biggest project currently weighs 500 KB (started in January), so there are a lot of headings.
With this proposed behavior (could be an option), I can start from the current day, at the bottom, and quickly navigate to the earlier days by just pressing Cmd+R (my shortcut for _Open in Symbol Mode_) and the Up arrow.

(In the same vein, to help fast keyboard-based navigation, the symbol switcher in Sublime and others also scroll the editor view to the selected heading in real-time, and scroll back to the cursor if the user cancels. Not sure if this belongs to another enhancement request/issue?)

**Comment by darlal** [comment] 2021-08-04 17:26
@oin if I understand, you're saying when the switcher is launched in Symbol mode, without any filter text, you'd like it to scroll to (if necessary) and pre-select whichever heading (1-6) symbol precedes the current cursor position. Currently, I think it selects the first symbol in the list. 

- What if there are other symbols (like links/embeds/ect..) between the nearest preceding header and the current cursor position, it should still select the header?
- If the cursor is currently on a heading, then I imagine, that heading would be selected

>Not sure if this belongs to another enhancement request/issue?)
Please create a separate issue for the the "preview scrolling". Thanks.

**Comment by oin** [comment] 2021-08-04 17:34
> you're saying when the switcher is launched in Symbol mode, without any filter text, you'd like it to scroll to (if necessary) and pre-select whichever heading (1-6) symbol precedes the current cursor position

Exactly what I meant.

> What if there are other symbols (like links/embeds/ect..) between the nearest preceding header and the current cursor position, it should still select the header?

Instinctively, I would make it select the header, because that's what I would like to happen in my use case.
But it'd be maybe more logical/simple to select whatever is the nearest preceding symbol that's in the list, and to also provide a setting to define what counts as a symbol.
This way, someone like me would set it up so that only headings are listed (not links/embeds/etc, as I don't care about them when navigating), and the behavior would be as expected.

> If the cursor is currently on a heading, then I imagine, that heading would be selected

Yes. That's what happens in Sublime Text, for instance (also in [my Folding Text plugin](https://github.com/oin/foldingtext-goto)).

**Comment by darlal** [comment] 2021-08-05 18:35
Thanks for the suggestion. I added this to the backlog.

**Comment by darlal** [comment] 2021-08-20 13:18
@oin this feature is available in the the [1.0.3 release](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.3). Check it out.

I will close this issue out. Thanks.

**Closed** 2021-08-23 03:15 UTC
Labels: enhancement

**Comment by oin** [comment] 2021-08-23 07:43
Huge thanks!

**Comment by FelipeRearden** [comment] 2021-09-03 12:04
Hello @darlal !!!!

Thanks for this new feature! I was waiting for the 0.12.15 public release to start to use and I have some info to share with you :)

- I’m using a new empty vault to show the situation. Take a look in my structure:
![h1](https://user-images.githubusercontent.com/85180696/132001336-9155f942-63d6-482b-9a75-99a678192187.png)

My expected Workflow for `Open in Headings Mode`
- Use a hotkey to navigate with keyboard with ALL headings ONLY in the ACTIVE NOTE
- Select the nearest header in the current cursor
 
This is my Settings screen:
![s1](https://user-images.githubusercontent.com/85180696/132001420-6e3244d3-6c79-41ea-a89a-7b707a0f42e6.png)
![s2](https://user-images.githubusercontent.com/85180696/132001433-26a169ac-d1e5-4340-b188-fa2461991b6c.png)
![s3](https://user-images.githubusercontent.com/85180696/132001442-ea91cc7c-cc69-4df1-9237-5bb48de20ff5.png)
![s4](https://user-images.githubusercontent.com/85180696/132001454-40c2156f-ab9d-45d1-b47b-44c1872ff558.png)


## Issues that I saw

Three things that I noted (I’m using Note 4 as my active note):

**01- List Mode is showing every note that have Headings inside instead of only headings from active note**
![h2](https://user-images.githubusercontent.com/85180696/132001533-223f6b52-6fc5-4be7-b471-9b64763b004c.png)
![h3](https://user-images.githubusercontent.com/85180696/132001546-29d26032-1535-4878-b7d6-45ee0d0eef23.png)

**02- List Mode is showing only H1 heading and not ALL headings from the active note**
![h3](https://user-images.githubusercontent.com/85180696/132002099-723b58d4-947e-4c43-b28c-287cfbc837c6.png)


**03 - If there is no H1, List Mode don’t show any heading from Active File**
![a2](https://user-images.githubusercontent.com/85180696/132001873-c5d498ef-f0eb-4e13-b261-7661ac0ee24a.png)
![a1](https://user-images.githubusercontent.com/85180696/132001894-636ca687-5a3e-4303-a289-d14bb534faaa.png)


—-

I’m sorry if I miss understood the new feature. I hope you could give me some guidance here :)

Thanks again for this amazing plug-in and have a great day!

**Comment by darlal** [comment] 2021-09-03 16:52
Hey @FelipeRearden From your screenshots, I think Headings mode is behaving as designed. I think you may be conflating Header mode and Symbol mode behaviors. Both deal with headers in some capacity, but to solve different problems.

Headings mode is meant to do with headers what the builtin (system) switcher does with filenames. The system switcher enables you to find files by searching through the filenames. However, many people don't use the filenames (for example, in Zettelkasten the filename is just a string of numbers), and instead use the first H1 contained in the note as the "title". This is the problem that Headings mode solves, it enables you to do everything the system switcher does with filesnames, but with the first H1 contained in the note instead. Here's some detail about each of the items you noted.

> 01- List Mode is showing every note that have Headings inside instead of only headings from active note

This is by design. When you just open the system switcher (without any filter text), or when you just open switcher++ (without any command) by default the most recent files opened are displayed. So in Headings mode, the same thing happens, but instead of showing the filenames, it shows the first H1 contained in the file.

> 02- List Mode is showing only H1 heading and not ALL headings from the active note

yep, by design. Headings mode without any filter text (so just `#` command and no other text), will behave as described above. There is an option to make it "fallback" to displaying the filename if the file does not contain any H1. When there is filter text (for example `#foo`), it can be configured to search through only H1 or all header levels contained in the file.

>03 - If there is no H1, List Mode don’t show any heading from Active File

yep, see the two points above. In this case, it is falling back to the filename because there is no H1 and no filter text.

>My expected Workflow for Open in Headings Mode
>   Use a hotkey to navigate with keyboard with ALL headings ONLY in the ACTIVE NOTE
>   Select the nearest header in the current cursor

To achieve this workflow, use Symbol mode instead of Headings mode. In Symbol mode settings, enable `Auto-select nearest heading` and only `Show Headings`, disable showing of the other symbols. This will do exactly what you describe in your workflow.

I hope this helps clarify things a bit. Happy to answer any other questions you have.

**Comment by FelipeRearden** [comment] 2021-09-03 17:28
Hello @darlal !!!!

Thanks for the reply ! It’s 300% crystal clear for me now ! 

Thanks for the spectacular clarification. Now I know how to use `Symbol List` and `Heading List` !
-  I tweaked `Symbol List` and worked exactly like you said.  
- `Heading List` is an amazing feature that I will introduce in my workflow too :)

From my tests, `1.0.3` is working perfect :)

Thank you so much for every time that you helped me !
