### ISSUE TITLE
Render titles same as default quick switcher

### ISSUE THREAD

**Issue by itsonlyjames** [darlal/obsidian-switcher-plus#180] opened 2024-10-03 23:31 UTC
Is there a way to achieve the same style? 
I can only seem to get the title without the preceding path. 

Default:
<img width="715" alt="image" src="https://github.com/user-attachments/assets/226f4b86-9678-40d0-86be-2f2e749c8696">

Switcher Plus default: 
<img width="717" alt="image" src="https://github.com/user-attachments/assets/f9d67755-1313-4d64-bb15-09ebda9c6111">

Closest I can get (missing parent path):
<img width="707" alt="image" src="https://github.com/user-attachments/assets/0743266a-2fb8-4618-81a1-1dfea739d2d4">

Update: did some digging and seems the path and basename are matched seperately, so this means for my wish to come true they'd need to be squished together. I'm trying to make sense of the hanlder file for path/title display but it's a beast! Keen to hear your thoughts @darlal.

**Comment by darlal** [comment] 2024-10-06 13:32
This can be achieved by disabling the setting [Override Standard mode behavior](https://github.com/darlal/obsidian-switcher-plus?tab=readme-ov-file#general-settings). That should stop the Obsidian single line rendering in Standard mode from being overridden.

Separately, this issue is a duplicate of discussion #176, so I'm going to close this one and we can continue to conversation in the discussion. Thanks!

**Closed by darlal** 2024-10-06 13:32 UTC
Labels: duplicate
