### ISSUE TITLE
Symbol search for Headings are not from the same page

### ISSUE THREAD

**Issue by noamsiegel** [darlal/obsidian-switcher-plus#91] opened 2022-12-10 23:30 UTC
Hello all,

**Issue:**
I'm having issues with navigating between headings on the _current_ open file

**Problem Steps**
Viewing file 2 → open Quick Switcher ++ → search "@" → shows headings from File 1

**Notes**
- Always shows me the last/previous page headings, not the current one
- Try switching the shortcuts from "@" to ")" — didn't work

**Fin**
Thanks in advance to anyone that was able to solve this! I haven't seen it anywhere else.

**Comment by darlal** [comment] 2022-12-11 12:24
Hey @noamsiegel  This is because when the trigger character `@` is typed, it acts upon the suggestion that is currently selected (highlighted) in the result list. The symbols displayed are from the suggestion file that was highlighted when you typed `@`. This is expected behavior and described in the [documentation](https://github.com/darlal/obsidian-switcher-plus#symbol-navigation-headings-hashtags-links-embeddings).

To get the symbol list for the active file, there are two options.

- Trigger the switcher open using the `Quick Switcher++: Open in Symbol Mode command`. This will auto-activate symbol mode for the active file. This command can be assigned to an Obsidian global hotkey.

- Type some filter text to have the target file show up in the result list, selected it, then type `@`. This will trigger symbol mode for highlighted suggestion.

**Closed** 2023-01-13 02:34 UTC
Labels: question
